In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import tensorflow as tf

In [2]:
dataset = pd.read_csv('Churn_Modelling.csv')
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [3]:
x = dataset.iloc[:,3:-1].values
y = dataset.iloc[:,-1].values

In [4]:
print(x)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [5]:
print(y)

[1 0 1 ... 1 1 0]


# Encoding categorical data

In [7]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
#Encoding gender
x[:,2] = le.fit_transform(x[:,2])
x

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

In [9]:
#One-hot Encoding geography
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
#the column is needed to be one hot encoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
x = np.array(ct.fit_transform(x))
x 

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

# Split the dataset into the training set and test set

In [10]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=0)

# Feature scaling

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [13]:
x_train

array([[-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [ 0.98560362, -0.5698444 , -0.57369368, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ...,
       [ 0.98560362, -0.5698444 , -0.57369368, ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
        -1.03227043,  0.32472465]])

# Building the ANN

## Initialiazing the ANN

In [14]:
ann = tf.keras.models.Sequential()

## Adding the input layer and the first hidden layer

In [31]:
#Units is the number of neurons in the first hidden layer
#activation is the activation function and relu means the rectifier function
ann.add(tf.keras.layers.Dense(units=10, activation='relu'))

## Adding the second layer

In [32]:
ann.add(tf.keras.layers.Dense(units=10, activation='relu'))

## Adding the output layer

In [33]:
# We use the dense class for all the layers because it is the way they are connected
# we just need 1 neuron because it is a binary prediction
# For the activarion we use sigmoid because it's a binary prediction, but if it would be a categorical prediction,
# we would use softmax
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Training the ANN

## Compiling the ANN

In [34]:
#for the loss function is necessary to use this one because is a binary prediction but if it would be a 
#categorical prediction we would use categorical_crossentropy
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

## Training the ANN on the training set

In [43]:
# The batch_size is 32 frequently
ann.fit(x_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
250/250 [==============================] - 3s 883us/step - loss: 0.3290 - accuracy: 0.8659
Epoch 2/100
250/250 [==============================] - 0s 844us/step - loss: 0.3297 - accuracy: 0.8650
Epoch 3/100
250/250 [==============================] - 0s 839us/step - loss: 0.3296 - accuracy: 0.8658
Epoch 4/100
250/250 [==============================] - 0s 829us/step - loss: 0.3293 - accuracy: 0.8650
Epoch 5/100
250/250 [==============================] - 0s 862us/step - loss: 0.3289 - accuracy: 0.8651
Epoch 6/100
250/250 [==============================] - 0s 838us/step - loss: 0.3292 - accuracy: 0.8656
Epoch 7/100
250/250 [==============================] - 0s 862us/step - loss: 0.3295 - accuracy: 0.8646
Epoch 8/100
250/250 [==============================] - 0s 835us/step - loss: 0.3292 - accuracy: 0.8661
Epoch 9/100
250/250 [==============================] - 0s 867us/step - loss: 0.3294 - accuracy: 0.8654
Epoch 10/100
250/250 [==============================] - 0s 835us/step - l

250/250 [==============================] - 0s 880us/step - loss: 0.3272 - accuracy: 0.8662
Epoch 80/100
250/250 [==============================] - 0s 816us/step - loss: 0.3278 - accuracy: 0.8658
Epoch 81/100
250/250 [==============================] - 0s 917us/step - loss: 0.3274 - accuracy: 0.8665
Epoch 82/100
250/250 [==============================] - 0s 824us/step - loss: 0.3275 - accuracy: 0.8656
Epoch 83/100
250/250 [==============================] - 0s 806us/step - loss: 0.3278 - accuracy: 0.8665
Epoch 84/100
250/250 [==============================] - 0s 803us/step - loss: 0.3275 - accuracy: 0.8654
Epoch 85/100
250/250 [==============================] - 0s 806us/step - loss: 0.3274 - accuracy: 0.8666
Epoch 86/100
250/250 [==============================] - 0s 844us/step - loss: 0.3271 - accuracy: 0.8665
Epoch 87/100
250/250 [==============================] - 0s 836us/step - loss: 0.3273 - accuracy: 0.8668
Epoch 88/100
250/250 [==============================] - 0s 822us/step - loss:

# Making the predictions and evaluating the model

In [36]:
test_loss, test_accuracy = ann.evaluate(x_test, y_test)

63/63 [==============================] - 3s 647us/step - loss: 0.3308 - accuracy: 0.8630


**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer?

In [37]:
x[0]

array([1.0, 0.0, 0.0, 619, 0, 42, 2, 0.0, 1, 1, 1, 101348.88],
      dtype=object)

In [38]:
predict_customer = sc.transform([[1.0, 0.0, 0.0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])

In [39]:
ann.predict(predict_customer)

array([[0.02409139]], dtype=float32)

Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

In [40]:
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


## Making the confusion matrix

In [41]:
from sklearn.metrics import confusion_matrix, accuracy_score

cm = confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[1536   59]
 [ 215  190]]


0.863